// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pztbzqbtlrmrkgdkmfuz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB6dGJ6cWJ0bHJtcmtnZGttZnV6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczODUyNDUsImV4cCI6MjA3Mjk2MTI0NX0.XGzLWB2dE950Ejnvx8lZtveK4jyYGP_44-pkxrf8kSE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});